version: "3.9"

services:
  db:
    image: postgres:16
    container_name: app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_local
    ports:
      - "5432:5432"
    volumes:
      - pgdata_app:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_local"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: app_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata_app:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  pgdata_app:
  redisdata_app:
